version: '3.8'
services:
  my-api:
    build: .
    container_name: my-api
    ports:
      - "3000:3000"
    environment:
      # Tambahkan variabel environment di sini jika diperlukan
      NODE_ENV: production
    restart: unless-stopped
    # volumes:
    #   - .:/app
    #   - /app/node_modules
